/** Hex only — Clerk cannot reliably resolve CSS `var()` and treats transparent as dark. */
export const clerkAppearance = {
  layout: {
    logoPlacement: "none",
    socialButtonsVariant: "blockButton",
    unsafe_disableDevelopmentModeWarnings: true,
  },
  variables: {
    colorPrimary: "#009276",
    colorBackground: "#f9fffd",
    colorInputBackground: "#ffffff",
    colorInputText: "#022020",
    colorText: "#022020",
    colorTextSecondary: "#3a5252",
    colorTextOnPrimaryBackground: "#ffffff",
    colorNeutral: "#022020",
    colorDanger: "#b42318",
    borderRadius: "12px",
    fontFamily: '"Libre Franklin", ui-sans-serif, system-ui, sans-serif',
    fontSize: "16px",
  },
  elements: {
    rootBox: { width: "100%" },
    cardBox: { width: "100%", boxShadow: "none" },
    card: {
      boxShadow: "none",
      backgroundColor: "#f9fffd",
      border: "1px solid #c7d9d4",
      padding: "24px",
    },
    headerTitle: { display: "none" },
    headerSubtitle: { display: "none" },
    logoBox: { display: "none" },
    footerPages: { display: "none" },
    footerAction: { display: "none" },
    footer: { display: "none" },
    footerItem: { display: "none" },
    formButtonPrimary: {
      backgroundColor: "#009276",
      color: "#ffffff",
      boxShadow: "none",
      fontSize: "15px",
      fontWeight: "600",
      height: "44px",
      textTransform: "none",
    },
    formFieldInput: {
      height: "44px",
      fontSize: "16px",
      backgroundColor: "#ffffff",
      color: "#022020",
      borderColor: "#c7d9d4",
    },
    formFieldLabel: {
      color: "#022020",
      fontSize: "14px",
      fontWeight: "500",
    },
    formFieldHintText: { color: "#3a5252", fontSize: "13px" },
    socialButtonsBlockButton: {
      height: "44px",
      backgroundColor: "#ffffff",
      color: "#022020",
      border: "1px solid #c7d9d4",
      boxShadow: "none",
    },
    dividerLine: { backgroundColor: "#c7d9d4" },
    dividerText: { color: "#3a5252" },
    identityPreviewText: { color: "#022020" },
    identityPreviewEditButton: { color: "#009276" },
  },
}
