/**
 * BraddCorp animated icon kit catalog.
 * Source: Lucide Animated (MIT) — Motion-powered, no attribution required.
 * Copy `components/icons/` + this file into other sites; depend on `motion`.
 */

export type IconSurface =
  | "nav"
  | "admin"
  | "registration"
  | "auth"
  | "content"
  | "feedback"
  | "marketing"

export type IconKitEntry = {
  id: string
  name: string
  /** Import path under `@/components/icons/` */
  file: string
  /** Component export name */
  component: string
  surfaces: IconSurface[]
  /** Where this shows up across BraddCorp products */
  usedOn: string
  /** Short product cue for the gallery */
  cue: string
}

export const ICON_SURFACES: {
  id: IconSurface
  label: string
  blurb: string
}[] = [
  {
    id: "nav",
    label: "Nav & chrome",
    blurb: "Headers, menus, theme toggles, home — every public and staff shell.",
  },
  {
    id: "admin",
    label: "Staff admin",
    blurb: "LECYC / Ren / Maddys / Camp Ruby dash — rows, filters, exports, settings.",
  },
  {
    id: "registration",
    label: "Registration",
    blurb: "Household flows, campers, payments, check-in, express re-register.",
  },
  {
    id: "auth",
    label: "Auth & security",
    blurb: "Clerk kit — lock, eye toggles, keys, logout, shield confirmations.",
  },
  {
    id: "content",
    label: "Content & files",
    blurb: "Docs, folders, uploads, copy links, edit forms, messages.",
  },
  {
    id: "feedback",
    label: "Feedback",
    blurb: "Success checks, delete confirms, refresh, activity pulses.",
  },
  {
    id: "marketing",
    label: "Marketing delight",
    blurb: "Light motion on CTAs, feature rows, and empty states — not hero Lottie.",
  },
]

/** Sites / products this kit is meant to land on. */
export const ICON_KIT_SITES = [
  { name: "braddcorp.com", role: "Source of truth (components/icons; /icons unlisted)" },
  { name: "LECYC", role: "Marketing + reg + staff admin" },
  { name: "Rendezvous IL", role: "Retreat site + reg + check-in + apps" },
  { name: "Maddy’s Foundation", role: "Site + team event registration" },
  { name: "Arnold Church of Christ", role: "Church site chrome" },
  { name: "Exhibit Evangelism", role: "Fair outreach + booth tools" },
  { name: "Church Relay", role: "Product UI + sales" },
  { name: "Pew Packers", role: "Games + coach home" },
  { name: "Camp Ruby demo", role: "Reg kit showcase" },
] as const

export const ICON_KIT: IconKitEntry[] = [
  {
    id: "home",
    name: "Home",
    file: "home",
    component: "HomeIcon",
    surfaces: ["nav"],
    usedOn: "All site headers & admin shells",
    cue: "Logo-adjacent home / dashboard",
  },
  {
    id: "menu",
    name: "Menu",
    file: "menu",
    component: "MenuIcon",
    surfaces: ["nav"],
    usedOn: "Mobile nav on every marketing + reg site",
    cue: "Hamburger open/close",
  },
  {
    id: "search",
    name: "Search",
    file: "search",
    component: "SearchIcon",
    surfaces: ["nav", "admin", "registration"],
    usedOn: "Admin tables, check-in, directories",
    cue: "Find camper / household / order",
  },
  {
    id: "bell",
    name: "Bell",
    file: "bell",
    component: "BellIcon",
    surfaces: ["nav", "admin"],
    usedOn: "Staff alerts, unread notices",
    cue: "Notifications",
  },
  {
    id: "settings",
    name: "Settings",
    file: "settings",
    component: "SettingsIcon",
    surfaces: ["admin", "nav"],
    usedOn: "Admin prefs, Cards/Rows toggles",
    cue: "Gear / site config",
  },
  {
    id: "sun",
    name: "Sun",
    file: "sun",
    component: "SunIcon",
    surfaces: ["nav"],
    usedOn: "Theme toggle (light)",
    cue: "Light mode",
  },
  {
    id: "moon",
    name: "Moon",
    file: "moon",
    component: "MoonIcon",
    surfaces: ["nav"],
    usedOn: "Theme toggle (dark)",
    cue: "Dark mode",
  },
  {
    id: "user",
    name: "User",
    file: "user",
    component: "UserIcon",
    surfaces: ["nav", "auth", "registration"],
    usedOn: "Account menu, parent profile",
    cue: "Single account",
  },
  {
    id: "users",
    name: "Users",
    file: "users",
    component: "UsersIcon",
    surfaces: ["admin", "registration"],
    usedOn: "Households, staff roster, volunteers",
    cue: "Groups / family",
  },
  {
    id: "id-card",
    name: "ID card",
    file: "id-card",
    component: "IdCardIcon",
    surfaces: ["registration", "admin"],
    usedOn: "Camper profiles, check-in badges",
    cue: "Attendee identity",
  },
  {
    id: "calendar-days",
    name: "Calendar",
    file: "calendar-days",
    component: "CalendarDaysIcon",
    surfaces: ["registration", "admin", "marketing"],
    usedOn: "Sessions, event dates, schedules",
    cue: "Dates & weeks",
  },
  {
    id: "map-pin",
    name: "Map pin",
    file: "map-pin",
    component: "MapPinIcon",
    surfaces: ["registration", "marketing"],
    usedOn: "Camp location, lodging, venue",
    cue: "Place",
  },
  {
    id: "cart",
    name: "Cart",
    file: "cart",
    component: "CartIcon",
    surfaces: ["registration"],
    usedOn: "Reg checkout, add-ons, merch",
    cue: "Checkout",
  },
  {
    id: "credit-card",
    name: "Credit card",
    file: "credit-card",
    component: "CreditCardIcon",
    surfaces: ["registration", "admin"],
    usedOn: "Payments, Stripe, balances",
    cue: "Pay / refund",
  },
  {
    id: "clipboard-check",
    name: "Clipboard check",
    file: "clipboard-check",
    component: "ClipboardCheckIcon",
    surfaces: ["registration", "admin"],
    usedOn: "Check-in, medical clearance, forms done",
    cue: "Complete checklist",
  },
  {
    id: "plus",
    name: "Plus",
    file: "plus",
    component: "PlusIcon",
    surfaces: ["admin", "registration"],
    usedOn: "Add camper, new row, create",
    cue: "Create",
  },
  {
    id: "square-pen",
    name: "Edit",
    file: "square-pen",
    component: "SquarePenIcon",
    surfaces: ["admin", "content"],
    usedOn: "Edit registration, inline row edit",
    cue: "Edit",
  },
  {
    id: "delete",
    name: "Delete",
    file: "delete",
    component: "DeleteIcon",
    surfaces: ["admin", "feedback"],
    usedOn: "Remove row, trash confirm",
    cue: "Destructive action",
  },
  {
    id: "copy",
    name: "Copy",
    file: "copy",
    component: "CopyIcon",
    surfaces: ["admin", "content"],
    usedOn: "Copy invite link, IDs, emails",
    cue: "Clipboard copy",
  },
  {
    id: "download",
    name: "Download",
    file: "download",
    component: "DownloadIcon",
    surfaces: ["admin", "content"],
    usedOn: "CSV export, badges, reports",
    cue: "Export",
  },
  {
    id: "upload",
    name: "Upload",
    file: "upload",
    component: "UploadIcon",
    surfaces: ["admin", "content", "registration"],
    usedOn: "Photo upload, medical docs",
    cue: "Import file",
  },
  {
    id: "folder-open",
    name: "Folder",
    file: "folder-open",
    component: "FolderOpenIcon",
    surfaces: ["admin", "content"],
    usedOn: "File drawers, media libraries",
    cue: "Open folder",
  },
  {
    id: "file-text",
    name: "File",
    file: "file-text",
    component: "FileTextIcon",
    surfaces: ["content", "registration", "admin"],
    usedOn: "Waivers, briefs, PDF views",
    cue: "Document",
  },
  {
    id: "mail-check",
    name: "Mail check",
    file: "mail-check",
    component: "MailCheckIcon",
    surfaces: ["admin", "registration", "feedback"],
    usedOn: "Confirmations sent, inbox status",
    cue: "Email delivered",
  },
  {
    id: "send",
    name: "Send",
    file: "send",
    component: "SendIcon",
    surfaces: ["admin", "content", "marketing"],
    usedOn: "Send email, share invite, contact forms",
    cue: "Submit / share",
  },
  {
    id: "message-circle",
    name: "Message",
    file: "message-circle",
    component: "MessageCircleIcon",
    surfaces: ["admin", "content", "marketing"],
    usedOn: "Chat, support, year directory messaging",
    cue: "Conversation",
  },
  {
    id: "lock",
    name: "Lock",
    file: "lock",
    component: "LockIcon",
    surfaces: ["auth"],
    usedOn: "Sign-in, protected routes",
    cue: "Secure",
  },
  {
    id: "key",
    name: "Key",
    file: "key",
    component: "KeyIcon",
    surfaces: ["auth"],
    usedOn: "Password / API keys / invite codes",
    cue: "Credentials",
  },
  {
    id: "eye",
    name: "Eye",
    file: "eye",
    component: "EyeIcon",
    surfaces: ["auth", "admin"],
    usedOn: "Show password, reveal PII",
    cue: "Visible",
  },
  {
    id: "eye-off",
    name: "Eye off",
    file: "eye-off",
    component: "EyeOffIcon",
    surfaces: ["auth"],
    usedOn: "Hide password",
    cue: "Hidden",
  },
  {
    id: "shield-check",
    name: "Shield check",
    file: "shield-check",
    component: "ShieldCheckIcon",
    surfaces: ["auth", "admin", "feedback"],
    usedOn: "Verified staff, medical OK, Turnstile success",
    cue: "Verified",
  },
  {
    id: "logout",
    name: "Log out",
    file: "logout",
    component: "LogoutIcon",
    surfaces: ["auth", "nav"],
    usedOn: "Account menu sign-out",
    cue: "Sign out",
  },
  {
    id: "check",
    name: "Check",
    file: "check",
    component: "CheckIcon",
    surfaces: ["feedback", "registration"],
    usedOn: "Inline success, step complete",
    cue: "Done",
  },
  {
    id: "circle-check",
    name: "Circle check",
    file: "circle-check",
    component: "CircleCheckIcon",
    surfaces: ["feedback", "registration", "marketing"],
    usedOn: "Success screens, feature bullets",
    cue: "Confirmed",
  },
  {
    id: "refresh-cw",
    name: "Refresh",
    file: "refresh-cw",
    component: "RefreshCWIcon",
    surfaces: ["feedback", "admin"],
    usedOn: "Reload table, sync payments",
    cue: "Reload",
  },
  {
    id: "activity",
    name: "Activity",
    file: "activity",
    component: "ActivityIcon",
    surfaces: ["admin", "feedback"],
    usedOn: "Live status, overview sparkline cue",
    cue: "Pulse / live",
  },
  {
    id: "chart-line",
    name: "Chart",
    file: "chart-line",
    component: "ChartLineIcon",
    surfaces: ["admin", "marketing"],
    usedOn: "Admin overview stats, sales pages",
    cue: "Metrics",
  },
  {
    id: "arrow-right",
    name: "Arrow right",
    file: "arrow-right",
    component: "ArrowRightIcon",
    surfaces: ["marketing", "nav", "registration"],
    usedOn: "CTAs, next step, case-study links",
    cue: "Continue",
  },
  {
    id: "external-link",
    name: "External link",
    file: "external-link",
    component: "ExternalLinkIcon",
    surfaces: ["marketing", "admin"],
    usedOn: "Open live site, Stripe dashboard",
    cue: "Opens elsewhere",
  },
  {
    id: "bookmark",
    name: "Bookmark",
    file: "bookmark",
    component: "BookmarkIcon",
    surfaces: ["admin", "content", "marketing"],
    usedOn: "Saved views, favorites",
    cue: "Save",
  },
  {
    id: "heart",
    name: "Heart",
    file: "heart",
    component: "HeartIcon",
    surfaces: ["marketing", "feedback"],
    usedOn: "Donate, favorited, thank-you states",
    cue: "Care / love",
  },
  {
    id: "sparkles",
    name: "Sparkles",
    file: "sparkles",
    component: "SparklesIcon",
    surfaces: ["marketing", "feedback"],
    usedOn: "New features, empty-state delight",
    cue: "Highlight",
  },
  {
    id: "zap",
    name: "Zap",
    file: "zap",
    component: "ZapIcon",
    surfaces: ["marketing", "registration"],
    usedOn: "Express re-register, fast path CTAs",
    cue: "Quick action",
  },
]
