#!/bin/sh
# Xcode Cloud: regenerate the Xcode project and optional Clerk override.
# Lives next to RendezvousIL.xcodeproj (ios/ci_scripts/).
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
IOS_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$IOS_ROOT"

echo "==> ios root: $IOS_ROOT"

# Optional: override Clerk key from Xcode Cloud environment secret.
if [ -n "${CLERK_PUBLISHABLE_KEY:-}" ]; then
  cat > "$IOS_ROOT/Config.local.xcconfig" <<EOF
// Generated by ci_post_clone.sh — do not commit
CLERK_PUBLISHABLE_KEY = ${CLERK_PUBLISHABLE_KEY}
EOF
  echo "Wrote Config.local.xcconfig from CLERK_PUBLISHABLE_KEY"
else
  echo "CLERK_PUBLISHABLE_KEY not set — using Config.xcconfig defaults"
fi

# project.yml is source of truth; regenerate so Cloud matches main.
if ! command -v xcodegen >/dev/null 2>&1; then
  echo "==> Installing XcodeGen"
  brew install xcodegen
fi

echo "==> xcodegen generate"
xcodegen generate

echo "==> ci_post_clone done"
