#!/bin/sh
# Xcode Cloud / CI: write Clerk key from environment into Config.local.xcconfig
set -eu

ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT="$ROOT/Config.local.xcconfig"

if [ -z "${CLERK_PUBLISHABLE_KEY:-}" ]; then
  echo "CLERK_PUBLISHABLE_KEY not set — using Config.xcconfig defaults"
  exit 0
fi

cat > "$OUT" <<EOF
// Generated by ci_post_clone.sh — do not commit
CLERK_PUBLISHABLE_KEY = ${CLERK_PUBLISHABLE_KEY}
EOF

echo "Wrote Config.local.xcconfig for CI"
